### ISSUE TITLE
code splitting css

### ISSUE THREAD

**Issue by rbenzazon** [sveltejs/rollup-plugin-svelte#100]
Hi,

As a big fan of svelte, I'm wanna say big up to its authors.
My question (not an issue) is can I code split the css bundle and have each component's css being lazy loaded ?
My project has 1 main App.svelte an 4 subsequent screens are built with code splitting (import()) and lazy loaded (I always need only one per session).
Now my only possible optimization is to have the scoped style code split at build time and lazy loaded.
I'm using rollup based on the default rollup template + some minor changes.
Note : I wanna keep the scoped style I just finished refactoring an unscoped vue project to svelte scoped syntax.
I have a the release coming up fast for a big ecommerce brand so I can't develop a custom solution so ideally I'm looking for an existing one.

**Comment by antony** [comment]
@rbenzazon this is more of a discussion for https://svelte.dev/chat. We aren't able to offer support for usage queries in github issues.

Regarding your question however - please have a look at the way Sapper works, since it does exactly this for your application. It might be a good pointer to get started.

**Comment by rbenzazon** [comment]
Hi,
Thanks for your help. As a newbie in svelte I have trouble choosing between svelte alone and and sapper. I stumble upon the solution, I just have to remove the css config property from the svelte plugin in the rollup config : 
`/*css: css => {
  css.write('public/build/bundle.css');
}*/`
svelte is great but It's a bit difficult to find all the basic learning resources, most of the obvious questions are not yet asked / answer and referenced by google.
I often find help on a topic but the solution is related to sapper but if you work on a client only project, I don't see how sapper will help. Looking at the intro of the documentation, it's not clear which project should benefit from using sapper and imagine you finish a project with svelte alone, I have no idea how would I convert it to sapper easily. It could be an axis of improvement to bring to the documentations.
