### ISSUE TITLE
breaking change

### ISSUE THREAD

**Issue by burningTyger** [sveltejs/rollup-plugin-svelte#103]
Commit 1ccd1e7ad18af8e86e764c5281846134295a51ec changed the behaviour my style sheet files are treated. For me it's a breaking change.

I have a few files some of which have css styles, some not but the root component uses a simple

```
<style>
  @import "../node_modules/bulma/css/bulma.css";
</style
```
to import and apply the bulma styles to my whole project. This doesn't work anymore with the latest change. The imorted style sheet is not applied at all. I'm not exactly sure why or how but when I compare the emitted css file it seems that in 5.1.1 the imported file was listed first in my bundle.css file and with the update it's listed later. Also the node_modules folder doesn't contain the bulma dir now compared to 5.1.1. That means it's not there and cannot be applied.

I hope this issue makes sense.

**Comment by burningTyger** [comment]
Now that 6.0 is out I tried again and worked around this issue with an `emitcss: true` and then adding the postcss plugin which solved it for me. I'm still not sure why it happened.

**Comment by benmccann** [comment]
Is there anything left to do here or should we close this?

**Comment by hmt** [comment]
It partially solved my issue. Just encountered a new bug where my app can't find a nested component's css file. Hadn't thought of that.

**Comment by benmccann** [comment]
Are you the same person as the original reporter? Is you app a Sapper app or a plain Svelte app?

**Comment by burningTyger** [comment]
It partially solved my issue. Just encountered a new bug where my app can't find a nested component's css file. Hadn't thought of that. (sorry wrong user ...)

**Comment by burningTyger** [comment]
Can we discuss on discord. Don't want to spam the issue
