### ISSUE TITLE
Plugin incompatible with Node.js `exports` package.json field

### ISSUE THREAD

**Issue by ctavan** [sveltejs/rollup-plugin-svelte#104]
This plugin tries to resolve the `package.json` files of processed modules: https://github.com/sveltejs/rollup-plugin-svelte/blob/85d25fbc78fab486373849548afddf6a80db8a95/index.js#L177-L180

This breaks with npm modules that make use of the [new `exports` field](https://nodejs.org/api/esm.html#esm_package_entry_points) but do not specify a subpath export for the `package.json` file.

This issue surfaced in https://github.com/uuidjs/uuid/issues/444

IMO this plugin can no longer expect that every npm module exports the `package.json` file and the resolver logic has to be adjusted accordingly.

Maybe in https://github.com/sveltejs/rollup-plugin-svelte/blob/85d25fbc78fab486373849548afddf6a80db8a95/index.js#L48-L55

we could add `ERR_PACKAGE_PATH_NOT_EXPORTED` as an "acceptable" error as well?

**Comment by jpaquim** [comment]
I was having the same problem with the `uuid` package, and implemented this PR https://github.com/sveltejs/rollup-plugin-svelte/pull/108 as a workaround. I only this discussion afterwards, but it seems like it follows in the direction you mentioned, of making it an acceptable error. I could use some feedback on the actual implementation though, there's probably a better way of getting the resolved file name other than parsing the error message.

**Comment by maxdobeck** [comment]
Another example: https://github.com/bvaughn/js-search
```
[!] (plugin svelte) Error: Package subpath './package.json' is not defined by "exports" in /home/.../node_modules/js-search/package.json

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/.../node_modules/js-search/package.json
```

**Comment by zwz** [comment]
And here is another one: https://github.com/marijnh/w3c-keyname/issues/10
