### ISSUE TITLE
Preprocess removes css for classes/elements which are added dynamically.

### ISSUE THREAD

**Issue by GeorgeTailor** [sveltejs/rollup-plugin-svelte#106]
By having something like this:      
```
<div id="arrow"></div>
<style type='text/scss'>
.red {
	color: red;
}
</style>
<script>
import { onMount } from 'svelte';
onMount(() => {
	const element = anotherElement.querySelector('#arrow');	
	element.classList.add('red');
});
</script>
```

and preprocessing with default `preprocess` option like so:      
```
preprocess: {
	style: ({ content, attributes }) => {
		if (attributes.type !== 'text/scss') return;
		return new Promise((fulfil, reject) => {
			sass.render({
				data: content,
				includePaths: ['zoo-modules/shared-module', 'src/common'],
				sourceMap: true,
				outFile: 'x' // this is necessary, but is ignored
			}, (err, result) => {
				if (err) return reject(err);
				fulfil({
					code: result.css.toString(),
					map: result.map.toString()
				});
			});
		});
	}
}
```

The `.red` class css rules are being deleted from final bundle.      
Is there an option how can this be worked around?      

A little more complicated example can be found here: https://github.com/zooplus/zoo-web-components/blob/zoo-grid-v2/zoo-modules/grid-module/GridPaginator.svelte.     
```
		&.next {
			svg {
				transform: rotate(-90deg);
			}
		}

		&.prev {
			svg {
				transform: rotate(90deg);
			}
		}
```
The above styles are being removed. The `svg` element is copied from template like so:
```
const arrowTemplateContent = gridPaginatorRoot.querySelector('#arrow').content;
gridPaginatorRoot.querySelector('.btn.prev').appendChild(arrowTemplateContent.cloneNode(true);
```

**Comment by Conduitry** [comment]
This is how scoped styles work in Svelte. It doesn't have anything to do with preprocessing or with the Rollup plugin. If you have questions about how this works, see https://github.com/sveltejs/svelte/issues/4802 or ask on SO or in our Discord chat server.

**Comment by GeorgeTailor** [comment]
What scoped styles have to do with this?
This is related to preprocessing, because the preprocessing stage is removing 'unused' css, not scoping.
There is no way to use Svelte's class toggling (as mentioned in sveltejs/svelte#4802), because I am using content from `template`.

What I am asking for is an option to disable css removal, which from preprocessor's point of view is unused. I haven't found anything about that in docs, so I raised an issue.

**Comment by Conduitry** [comment]
If it's the preprocessor removing the styles, that would be something to take up with that preprocessor. This plugin doesn't do any removing of styles itself.

**Comment by GeorgeTailor** [comment]
My mistake, it is Svelte that removes those style and it is related to scoping.
But, in this case, I build web-components, where style are scoped inside element by default, so there is no need for Svelte to scope them and remove unused ones.
Anyway, is there a way right now to force Svelte not to remove styles?

**Comment by antony** [comment]
@GeorgeTailor you can use `:global()` around your style name

**Comment by GeorgeTailor** [comment]
`:global()` is not an option for customElements.
