### ISSUE TITLE
Types aren't published

### ISSUE THREAD

**Issue by robcresswell** [sveltejs/rollup-plugin-svelte#110]
Hi! I'm probably overlooking something here, but it seems like the types that are part of this repo are not being published, so they can't be consumed. I think this is due to https://github.com/sveltejs/rollup-plugin-svelte/blob/master/package.json#L7

**Comment by Tharit** [comment]
Just stumbled upon the same issue.
Would be great if you could add them in the next version as this triggers an error in one of our build steps.

**Comment by Conduitry** [comment]
Sorry about that! They are now included in 5.2.3 - https://unpkg.com/rollup-plugin-svelte@5.2.3/index.d.ts
