### ISSUE TITLE
css file written to wrong output folder

### ISSUE THREAD

**Issue by Gamadril** [sveltejs/rollup-plugin-svelte#128]
my config:
```
import svelte from 'rollup-plugin-svelte'
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

export default {
    input: 'src/main.js',
    output: {
        file: 'js/main.min.js',
        name: 'app',
        format: 'iife'
    },
    plugins: [
        svelte({
	    css: css => {
		css.write('css/bundle.css', false);
	    }
        }),
        resolve({
	    browser: true,
	    dedupe: ['svelte']
	}),
	commonjs()
    ]
};
```

I expect that `css.write('css/bundle.css', false);` writes the css file relative to the root folder. Actually it is writing it relative to the output folder of the js file: 'js/css/bundle.css'.

**Comment by Gamadril** [comment]
I think this change was a mistake. If someone wants the cssfile to go into the output directory, the right path is to provide in that case. And from the name of the `output.file` property it's not clear at all, that the first part of the path is automatically used as output folder....

**Comment by Conduitry** [comment]
Having the paths be relative to the main output directory is intentional, and aligns with the paths in the built-in asset handling feature of Rollup, which this plugin now uses as of version 6.0.0. Yes this can make for a confusing upgrade between v5 and v6, but the new behavior is listed in the readme, and is also described in the changelog.

**Comment by matths** [comment]
@Conduitry, it is definitely confusing and it doesn't answer the question on how to achieve the desired behavior of @Gamadril  at all? So how can the css file be in a css/ not js/css/ while the javascript file goes to js/?

**Comment by ekhaled** [comment]
@Gamadril @matths did you manage to find a way around this?

@Conduitry what is the convention on outputting to separate folders as per OP?

**Comment by ValeTheVioletMote** [comment]
This issue shouldn't be closed.

That said, here's a cheap workaround that I'm using, @ekhaled @matths 

```js
svelte({dev: true, css: css => {
            const css_name = 'compiled.css',
                stupid_ouput_dir = 'static/js',
                sensible_output_dir = 'static/css',
                fs = require('fs'),
                output_css = stupid_ouput_dir+"/"+css_name,
                output_map = output_css+".map";

            css.write(css_name);
            var attempts = 0
            , max_attempts = 4;

            setTimeout(function check_for_css(){
                if(fs.existsSync(output_css) && fs.existsSync(output_map)) {
                    fs.renameSync(output_css, sensible_output_dir+"/"+css_name);
                    fs.renameSync(output_map, sensible_output_dir+"/"+css_name+".map");
                }else{
                    if(attempts < max_attempts) {
                        setTimeout(check_for_css, 250);
                    }
                }
            }, 250);
        }})
```

**Comment by benmccann** [comment]
We're planning to remove the `css` option. A better way to handle is to emit the CSS styles into a virtual file (via `emitCss: true`), and have another Rollup plugin – for example, [`rollup-plugin-css-only`](https://www.npmjs.com/package/rollup-plugin-css-only), [`rollup-plugin-postcss`](https://www.npmjs.com/package/rollup-plugin-postcss), etc. – take responsibility for the new stylesheet.

**Comment by zalito12** [comment]
I write my js to ``assets/js/main.js`` and my styles to ``assets/css/styles.css``.

```
import fs from 'fs';

...
  output: {
     ...
    file: "assets/js/main.js"
  },
...
    css({
      output(styles) {
        fs.writeFileSync(
          "assets/css/styles.css",
          styles
        );
      }
    }),
```
