### ISSUE TITLE
How to treeshake properly when importing libraries into components?

### ISSUE THREAD

**Issue by winston0410** [sveltejs/rollup-plugin-svelte#129]
Hi,

How can I config treeshaking correctly for imported libraries?  I found out that the treeshaking doesn't work with the imported libraries, and I have already tried explicitly set `treeshake` to `true` in Rollup's setting.

The way for me to import is this:
```javascript
import * as R from 'ramda'
```

**Comment by mhatvan** [comment]
It is described here how to import individual methods only: https://www.npmjs.com/package/ramda#usage

**Comment by Conduitry** [comment]
This is unrelated to Svelte, and would be a question for Ramda or Rollup.
