### ISSUE TITLE
Missing entry dev in interface Options

### ISSUE THREAD

**Issue by floratmin** [sveltejs/rollup-plugin-svelte#143]
In the type definition file index.d.ts the interface `Options` misses the key `dev?: boolean`.

**Comment by benmccann** [comment]
`interface Options extends CompileOptions`, which includes `dev`: https://github.com/sveltejs/svelte/blob/10f68289ba55a21d47e45af24175eaae5b04149a/src/compiler/interfaces.ts#L117

The change hasn't yet been released however. Hopefully it will be soon
