### ISSUE TITLE
CSS stops working when I update to the latest version of rollup-plugin-svelte?

### ISSUE THREAD

**Issue by xabru** [sveltejs/rollup-plugin-svelte#148]
In the example below:

https://github.com/mvolkmann/svelte-and-sapper-in-action/tree/master/travel-packing-ch4

I update all the dependencies and I have found a problem with the "rollup-plugin-svelte" plugin when updating to the latest version "v6.1.0" breaks the CSS code, if I downgrade to the version "v5.2.3" it is solved.

Can someone more experienced check and see what happens?

**Comment by lukeed** [comment]
See [`rollup-plugin-svelte@6.0.0` release notes](https://github.com/sveltejs/rollup-plugin-svelte/blob/master/CHANGELOG.md#600)

```diff
output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
--		file: 'public/build/bundle.js'
++		file: 'build/bundle.js'
	},
```
