### ISSUE TITLE
Plugin option types out of date

### ISSUE THREAD

**Issue by chrstntdd** [sveltejs/rollup-plugin-svelte#150]
Hey folks, I'm noticing that the published type declarations seem to be out of date with the plugin options that are documented in the README.md. 

Specifically, I'm noticing the mismatch with the `hydratable` option. It is not present on the `Options` interface, but it is kinda referenced within `Options["compilerOptions"]`. Additionally, `generate` is also missing, but declared within `compilerOptions` in the same way, yet the types line up when I'm using it.

![image](https://user-images.githubusercontent.com/17863654/97434801-edc38500-18f5-11eb-8b74-e2f9320f7ca6.png)

I'm not sure of the right approach to this, but I would be willing to make this change and have the types match up with the public API.

My first thought was to sort of spread out the `compilerOptions` up one level, but that also looks like it would conflict with what [the plugin is doing under the hood](https://github.com/sveltejs/rollup-plugin-svelte/blob/master/index.js#L88)

```ts
// index.d.ts

interface Options {
  // ...
  hydratable:  CompileOptions['hydratable']
  generate:  CompileOptions['generate']
  // ...
}
```

Any thoughts?

Versions:
```
"svelte": "^3.29.4"
"rollup": "^2.32.1",
"rollup-plugin-svelte": "^6.1.0"
```

**Comment by lukeed** [comment]
Hey,

Same-ish answer as https://github.com/sveltejs/template/issues/180#issuecomment-716035699

Currently `master` is unreleased, so any use of `compilerOptions` is not supported until 7.0 comes out.
Before than, any `6.x` branch had an incomplete set of type definitions to begin with. This PR (https://github.com/sveltejs/rollup-plugin-svelte/pull/126) was meant to fix that, but in order for it to work consistently, it had to ensure a minimum requirement for `svelte/compiler`, which was a breaking change & kickstarted the 7.0 rc

You can send in PR on the `6.x` branch to manually type the old options. Or you can just throw a `@ts-ignore` above the unknown options 😆 

Hope that helps~!
