### ISSUE TITLE
version 7.0.0 `compilerOptions` breaks preprocess

### ISSUE THREAD

**Issue by benji014628** [sveltejs/rollup-plugin-svelte#160]
This is the [repo](https://github.com/benji014628/code-challenges) I'm using with tailwindcss and sapper-rollup template from https://github.com/andrasbacsai/sapper-tailwind-starter. I ran `npm run dev` and got this error:
![Screen Shot 2020-11-25 at 09 29 35](https://user-images.githubusercontent.com/44789941/100262264-c534a800-2f00-11eb-9d43-a3d5caa96bb9.png)

**Comment by Conduitry** [comment]
The current template in https://github.com/sveltejs/template, which can be converted to TypeScript mode, uses version 7 of this plugin as well as a preprocessor, and works fine. The official Sapper template hasn't been updated yet.

We obviously can't make any guarantees about any third party template. Updating to version 7 of this plugin won't be as simple as just updating your package.json (that's what it means to be a breaking change), and any updates will be the responsibility of the maintainers of that template.

**Comment by lukeed** [comment]
You need to move the config keys into `compilerOptions` namespace inside your `rollup.config.js` file

```diff
svelte({
--  dev,
--  hydratable: true,
--  emitCss: true,
++ compilerOptions: {
++   dev,
++   hydratable: true,
++   emitCss: true,
++ },
  preprocess
}),
```

You have two of these – one in `client` and `server` options.

**Comment by benmccann** [comment]
Here's a PR to upgrade sapper-template that you can use as an example: https://github.com/sveltejs/sapper-template/pull/289

**Comment by benji014628** [comment]
> You need to move the config keys into `compilerOptions` namespace inside your `rollup.config.js` file
> 
> ```diff
> svelte({
> --  dev,
> --  hydratable: true,
> --  emitCss: true,
> ++ compilerOptions: {
> ++   dev,
> ++   hydratable: true,
> ++   emitCss: true,
> ++ },
>   preprocess
> }),
> ```
> 
> You have two of these – one in `client` and `server` options.

yeah I did that in the repo....

**Comment by benji014628** [comment]
Most people read the repo before suggesting a solution

**Comment by lukeed** [comment]
Most people don't include useless links in their report.
"I'm using X ... but not really"

**Comment by benmccann** [comment]
I was able to reproduce this and saw a couple other people report it on Discord. Unfortunately, I'm not quite sure where the error is coming from. It's unclear to me that it's coming from `rollup-plugin-svelte`. Sapper's error messages are useless when running `npm run dev` and I can't reproduce this with `npm run build`, which means it's next to impossible to debug. I think I would advise just sticking to 6.0.0 for now and we'll make sure 7.0.0 works with SvelteKit. I don't really want to sink time into fixing Sapper's error handling when Sapper is going away

**Comment by benji014628** [comment]
> I was able to reproduce this and saw a couple other people report it on Discord. Unfortunately, I'm not quite sure where the error is coming from. It's unclear to me that it's coming from `rollup-plugin-svelte`. Sapper's error messages are useless when running `npm run dev` and I can't reproduce this with `npm run build`, which means it's next to impossible to debug. I think I would advise just sticking to 6.0.0 for now and we'll make sure 7.0.0 works with SvelteKit. I don't really want to sink time into fixing Sapper's error handling when Sapper is going away

wait what do you mean sapper is going away?

**Comment by antony** [comment]
@benji014628 https://svelte.dev/blog/whats-the-deal-with-sveltekit

**Comment by benmccann** [comment]
This looks to be an issue in Svelte core: https://github.com/sveltejs/svelte/issues/5722
