### ISSUE TITLE
How i do include node_modules

### ISSUE THREAD

**Issue by si3nloong** [sveltejs/rollup-plugin-svelte#170]
I'm importing some svelte lib, and they did include `svelte` on package.json. But it seem like `rollup-plugin-svelte` doesn't transpile it. Any idea how can i include `node_modules` and let `rollup-plugin-svelte` do the job?

<img width="866" alt="Screenshot 2020-12-22 at 10 08 35 PM" src="https://user-images.githubusercontent.com/28108597/102897364-d4c4f380-44a2-11eb-8459-aeef274224c7.png">

**Comment by Conduitry** [comment]
It looks like the issue is that they wrote it in TypeScript but you're not transpiling that during the build.

GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
