### ISSUE TITLE
warning "@snowpack/plugin-svelte > rollup-plugin-svelte@7.0.0" has unmet peer dependency "rollup@>=2.0.0"

### ISSUE THREAD

**Issue by Valexr** [sveltejs/rollup-plugin-svelte#174]
warning "@snowpack/plugin-svelte > rollup-plugin-svelte@7.0.0" has unmet peer dependency "rollup@>=2.0.0"

**Comment by Conduitry** [comment]
This sounds like a question for the Snowpack plugin, if they're using this plugin. rollup-plugin-svelte does indeed have a peerdep on Rollup 2+.

**Comment by benmccann** [comment]
Here's their `package.json`. I don't see anything obviously wrong there. Though I'm not sure what version of Snowpack and `@snowpack/plugin-svelte` you're using, so perhaps you have an older version that what's checked in. https://github.com/snowpackjs/snowpack/blob/main/plugins/plugin-svelte/package.json
