### ISSUE TITLE
publish release 7.1.0

### ISSUE THREAD

**Issue by milahu** [sveltejs/rollup-plugin-svelte#175]
preprocessor-sourcemap support from #157 is needed

**Comment by Conduitry** [comment]
What specifically would happen in this project as part of 7.0.1?

**Comment by dummdidumm** [comment]
I think he means that #157 (merged 25-11) did not make it into `7.0.0` (released 23-11), and in order to support source maps from preprocessors (which Svelte now supports) we need another release. Probably should be `7.1.0` btw because it's a new feature.

**Comment by benmccann** [comment]
New releases have been cut for many of the non-core projects including this one
