### ISSUE TITLE
Please maintain backwards compatibility 

### ISSUE THREAD

**Issue by jeffRTC** [sveltejs/rollup-plugin-svelte#176]
My app no longer build with your new version.

```
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file - better for performance
			css: css => {
				css.write('public/build/bundle.css', false);
			}
		}),
```

```
[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "css" option. Please use "compilerOptions" for any Svelte compiler configuration.
```

Breaking things like this bad for **_future_** of **Svelte**. If you look at Windows, an app made in 1999 can still run on Windows 10. 

I don't know why younger generation don't care about this!!

**Comment by lukeed** [comment]
Versioning exists for a reason. Breaking changes are permitted and held for major semver bumps – eg, 6.x.x -> 7.x.x

**Comment by jeffRTC** [comment]
@lukeed I wrote my app a year ago and it's broken today. What a state of Svelte. Sad..

I'm canceling all my future projects with svelte.

I re-call this didn't happen with other frame works I worked with. 

@Rich-Harris 

Enterprise will never adopt sveltejs for this very reason!

**Comment by jeffRTC** [comment]
@lukeed 

In professional development, Versions doesn't break already working ones. For example, I can use C++03 in C++11 without any issues.

**Comment by lukeed** [comment]
Semver is not unique to Svelte, lol. At least 95% of the npm ecosystem is following the same tactics (it's encouraged at the ecosystem level). And Svelte itself is a package – not a language.

Pin your versions. Use lock files. Or follow any changelog. You have so many options to choose from, you're not helpless here. Good luck~!

**Comment by jeffRTC** [comment]
@lukeed 

"Svelte itself is a package – not a language"

What's your point?

Backwards compatibility applies to almost anything in professional software development world.   Operating Systems, Frameworks, Languages, Libraries etc

Either way, this is horrible and a bad practice. Just because it's encouraged at ecosystem level doesn't means you have to follow it blindly.

https://medium.com/@graeme_boy/semantic-versioning-is-for-losers-67bf294ace85

**Comment by jeffRTC** [comment]
@lukeed  @Rich-Harris 

Turns out a lot of things broken not just this plugin. The lib itself. 

This is like living next to SUN. You don't know when it hit you!

**Comment by Conduitry** [comment]
Running an open source project is indeed like living next to the sun. We never know when people like you will open issues.
