### ISSUE TITLE
Migration documentation

### ISSUE THREAD

**Issue by stefanovualto** [sveltejs/rollup-plugin-svelte#177]
Dear contributors,

Thank you for working at making svelte a great tool.

I am trying to update my current project based on this (great) template (not made by me) https://github.com/redradix/svelte-custom-element-template . Which work around the webcomponent issues described in the README.

But I am struggling in trying to find a way to replace that line https://github.com/redradix/svelte-custom-element-template/blob/master/scripts/build.js#L66 using css-only or postcss plugin, I am probably missing something in how to achieve this.

Can you help me or the community by explaining what I should do in that use case or by documenting what changes and how to migrate from one major version to another?

Sorry to bother you, but I think that svelte is a great tool and I really would like to have a solution with web component that uses the strength of svelte.

Thank you in advance for your help.

**Comment by benmccann** [comment]
Please see https://github.com/sveltejs/rollup-plugin-svelte/blob/master/CHANGELOG.md#700

**Comment by stefanovualto** [comment]
Thank you!

I am still not sure how to upgrade this template, but I will give a try...

**Comment by benmccann** [comment]
You can look at the svelte template for an example

**Comment by stefanovualto** [comment]
I already look at it and it didn't help.

because this specific template try to hack the web component implementation of svelte to have a unique webcomponent that wrap a full svelte app (on of the tricky part is the injection of the css into the shadowdom root style...

If you have a simple solution for that I am more than interested :) And I guess I won't be the only one...
