### ISSUE TITLE
(!) Plugin commonjs--resolver: It appears a plugin has implemented a "resolveId" hook that uses "this.resolve" without forwarding the third "options" parameter of "resolveId"

### ISSUE THREAD

**Issue by josdejong** [sveltejs/rollup-plugin-svelte#207]
After upgrading from  `7.1.2` to `7.1.3` I get the following warning when using rollup:

> (!) Plugin commonjs--resolver: It appears a plugin has implemented a "resolveId" hook that uses "this.resolve" without forwarding the third "options" parameter of "resolveId". This is problematic as it can lead to wrong module resolutions especially for the node-resolve plugin and in certain cases cause early exit errors for the commonjs plugin.
> In rare cases, this warning can appear if the same file is both imported and required from the same mixed ES/CommonJS module, in which case it can be ignored.

I'm not sure if this is caused by `rollup-plugin-svelte` itself or a side effect from an other plugin. Any idea how to pinpoint this? Can it be casused by this commit https://github.com/sveltejs/rollup-plugin-svelte/commit/3be2d583515f2c63d43385179339946178563bd7?

**Comment by dummdidumm** [comment]
Yeah it's probably from that commit - I'm not sure how to work around this / how to silence the error because it's essentially a false postive

**Comment by josdejong** [comment]
Probably, 

```js
async resolveId(importee, importer) {
  // ...
  const resolved = await this.resolve(importee, importer, { skipSelf: true });
  //...
}
```

Should be changed to something like:

```js
async resolveId(importee, importer, options) {
  // ...
  const resolved = await this.resolve(importee, importer, { skipSelf: true, ...options });
  //...
}
```
