### ISSUE TITLE
Handle warnings is not working?

### ISSUE THREAD

**Issue by socketopp** [sveltejs/rollup-plugin-svelte#212]
[How can we disable svelte warnings? (a11y, etc)
](https://github.com/sveltejs/language-tools/issues/650)Any fix regarding this?

**Comment by Conduitry** [comment]
I don't know what that language-tools issue has to do with this project, but if the question is specifically how you can stop rollup-plugin-svelte from emitting Rollup warnings during build time, you can already do this with the `onwarn` callback in the plugin in your Rollup config. https://github.com/sveltejs/rollup-plugin-svelte#usage
