### ISSUE TITLE
Mention that successfully bundling requires rollup-plugin-node-resolve

### ISSUE THREAD

**Issue by eddieantonio** [sveltejs/rollup-plugin-svelte#54]
I'm a super n00b at this Rollup thingymobobber, but I've been trying to build my own app using Svelte from scratch — WITHOUT using a boilerplate. I tried copy-pasting the example in the README.md, but it didn't work. Rollup was giving me this error:

```sh
$ npx rollup -c  

src/main.js → dist/bundle.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency
svelte/internal (imported by src/main.js, src/App.svelte)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
svelte/internal (guessing 'internal')
created dist/bundle.js in 76ms
```

I tried importing `svelte/internal` in node, and it worked fine. Eventually, I looked at some GitHub examples of Svelte 3 + Rollup, and found this plugin required for ALL of them: `rollup-plugin-node-resolve`. I popped it into my config:

```js
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';

export default {
  input: 'src/main.js',
  output: {
    file: 'dist/bundle.js',
    format: 'iife'
  },
  plugins: [
    svelte({
      // You can restrict which files are compiled
      // using `include` and `exclude`
      include: 'src/**/*.svelte',
    }),
    resolve()
  ]
}
```

And everything worked!

# ACTION ITEM

State in the README that `rollup-plugin-node-resolve` is required and must be used to have a fully working `rollup.config.js`.

**Comment by patoi** [comment]
`npm i -D rollup-plugin-commonjs` and add to config file:

1. import commonjs from 'rollup-plugin-commonjs'
2. commonjs()

```javascript
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
// install with: npm i -D rollup-plugin-commonjs
import commonjs from 'rollup-plugin-commonjs'

export default {
  input: 'src/main.js',
  output: {
    file: 'dist/bundle.js',
    format: 'iife'
  },
  plugins: [
    svelte({
      // You can restrict which files are compiled
      // using `include` and `exclude`
      include: 'src/**/*.svelte',
    }),
    resolve(),
    commonjs()
  ]
}```

**Comment by ghosh** [comment]
I'm getting the same error when I install this in a yarn workspace. However, it works properly when I install it via `npx degit ...`

**Comment by mikestead** [comment]
@ghosh same issue here re workspaces

**Comment by mikestead** [comment]
For anyone else that hits this issue when using yarn workspaces, you can work around it by [avoiding the hoisting](https://yarnpkg.com/blog/2018/02/15/nohoist) of `rollup-plugin-svelte`

```json
"workspaces": {
    "packages": [ "packages/*" ],
    "nohoist": [
      "**/rollup-plugin-svelte",
      "**/rollup-plugin-svelte/**"
    ]
  }
```

**Comment by mihar-22** [comment]
Just a note here that when using Yarn Workspaces, because the packages are symlinked they are resolved absolutely, so `rollup-plugin-svelte` doesn't resolve the `.svelte` files if a `module` key is defined in `package.json` and files are present, even if a `svelte` key is defined. 

I fixed it by adding `mainFields: ['svelte', 'module', 'main']` (order is important!) to  `@rollup-plugin-node-resolve` which is documented [here](https://github.com/rollup/plugins/tree/master/packages/node-resolve#mainfields). I think it'd be safer to just have this set regardless if you're using Workspaces or not.

**Comment by CircleOnCircles** [comment]
I observed this in my electron-svelte app.

instead of 

```bash
yarn run autobuild
```

```bash
npm run autobuild
```

did solved my issue.
Noted that `autobuild` script is defined as `rollup -c -w`

**Comment by elimisteve** [comment]
[This](https://github.com/sveltejs/rollup-plugin-svelte/issues/54#issuecomment-509684264) worked for me, except replacing the archived/deprecated `rollup-plugin-commonjs` with `@rollup/plugin-commonjs`, then ensuring that `@rollup/plugin-commonjs` is running the latest version.

Specifically upgrading `@rollup/plugin-commonjs` from version `11.0.0` to `11.1.0` fixed everything!
