### ISSUE TITLE
Transition unused import warning

### ISSUE THREAD

**Issue by bravecow** [sveltejs/rollup-plugin-svelte#81]
I am not sure it should be in `rollup-plugin-svelte` repository.

Warning in console:

`slide imported from external module 'svelte/transition' but never used`

but it is used in `transition` attribute:

![image](https://user-images.githubusercontent.com/988471/69345171-5e3f3c00-0c79-11ea-909f-3f2fdb6b9c9f.png)

**Comment by antony** [comment]
This doesn't relate to the rollup plugin and is an error in your project.

**Comment by bravecow** [comment]
Okay, it can be not related to rollup plugin, but there is no error. Your answer just looks like polite "fck off" 👍
