### ISSUE TITLE
Moving to Monorepo

### ISSUE THREAD

**Issue by shellscape** [sveltejs/rollup-plugin-svelte#82]
@Rich-Harris @Conduitry @tivac 

I'd like to begin the process of moving the plugin to the new monorepo. There are a number of issues and PRs that are open and/or have gone unaddressed. Is there any chance you all can button those up this week so that the plugin folks can begin the move process? Given the community behind Svelte and this being one of the more active Rollup plugins, I'd like to get buy in from you all on when it's OK to proceed.

**Comment by Rich-Harris** [comment]
closing this as the repo was moved to the sveltejs org
