### ISSUE TITLE
ValidationError: Classes can only be applied to DOM elements, not components

### ISSUE THREAD

**Issue by karlitos** [sveltejs/rollup-plugin-svelte#83]
In my setup I use the _rollup-plugin-svelte_  and for the client-side routing I tried the [svero](https://github.com/kazzkiq/svero) svelte router. Apparently, passing a _class_ attribute to  component should be possible, see kazzkiq/svero#13 and kazzkiq/svero@26b48a6

When I try to use it as in the example from kazzkiq/svero#45 I got following compile error:

```bash
rollup v1.27.0
bundles src/main.js → public/bundle.js...
[!] (plugin svelte) ValidationError: Classes can only be applied to DOM elements, not components
src/components/Navbar.svelte
38:         <ul class="navbar-nav mx-auto">
39:             <li class="nav-item mx-2">
40:                 <Link href={MAIN_PATH} class:active={path.includes(MAIN_PATH)}>
                                           ^
41:                     Feedback
42:                 </Link>
ValidationError: Classes can only be applied to DOM elements, not components
```

I do not think this is actually related to _svero_ but probably to the _rollup-plugin-svelte_

**Comment by alexdilley** [comment]
The prop is `className`? ([Link component](https://github.com/kazzkiq/svero#link-component)/[source](https://github.com/kazzkiq/svero/blob/master/src/Link.svelte).) And you won't be able to use the class _directive_ since it's a component.

**Comment by karlitos** [comment]
Well, [this comment](https://github.com/kazzkiq/svero/issues/13#issuecomment-490490652) states, that it should actually be possible.

An when using the `className' attribute I encounter other issues (css classes not bundled) as described in [my comment](https://github.com/kazzkiq/svero/issues/45#issuecomment-561733000).

**Comment by alexdilley** [comment]
Sorry, yes, this [line](https://github.com/kazzkiq/svero/blob/master/src/Link.svelte#L10) allows `class` to be provided as a prop. You can't use it in directive form though, so it will need to be:

```html
class="{path.includes(MAIN_PATH) ? 'active' : ''}"
```

**Comment by karlitos** [comment]
Oh, many thanks, now I understand the difference between _prop_ `class` and _directive_ `class:` 😃 

Anyhow, the issue with css-classes, defined in the `<style>` section not being included/bundled when passing the class-name as prop persist, but it's not directly related to the rollup plugin. Or is there same clever way to enforce it ?

I can still include the styles in the __global.css__, which I don't like that much. But since the whole `.active` styling is not working reactively as it should I will probably now stop trying.

**Comment by alexdilley** [comment]
```html
<style>
  :global(a.active) {
    /* ... */
  }
</style>
```

should work. This is expected behaviour nonetheless.

**Comment by karlitos** [comment]
Thanks for clarification 👍  closing now
