### ISSUE TITLE
Access to parsed templates

### ISSUE THREAD

**Issue by cibernox** [sveltejs/rollup-plugin-svelte#87]
This is more a question than an issue, but I want to explain what I want to achieve and how I found tooling less than ideal.

In the react and ember community there is a known "Good Practice™" of using the so called _test selectors_ to match against during tests.

The idea is that not always the elements you want to target will have a specific enough or practical CSS selector that you can use in tests to target your assertions. 

Instead of adding an otherwise unnecessary CSS class to the elements just for the sake of testing and will just be dead weight in production, there is the convention that `data-test-*` attributes can safely be stripped in production builds. 

The main plugins to achieve that are https://github.com/simplabs/ember-test-selectors in Ember and https://www.npmjs.com/package/babel-plugin-react-remove-properties in React.

I want to get the same functionality and I wrote this simple preprocessor:

```js
// rollup.config.js of my sapper app
const dev = mode === 'development';

const testSelectorsProprocessor = !dev ? {
  markup({ content, filename }) {
    let code = content.replace(/ data-test-[^>\ ]*(="[^"]")?(='[^']')?/g, '');
    return Promise.resolve({ code });
  }
} : {};
export default {
  client: {
    input: config.client.input(),
    output: config.client.output(),
    plugins: [
      replace({
        "process.browser": true,
        "process.env.NODE_ENV": JSON.stringify(mode)
      }),
      svelte({
        dev,
        hydratable: true,
        emitCss: true,
        preprocess: [testSelectorsProprocessor] // <---- here
      }),
      ...
  }
}
```

**It works**, but using regular expressions makes me nervous. There are many things that can go wrong with regular expressions. This specific example is doable as there aren't that many things that match: `<div data-test-whatever>`, `<div data-test-whatever="foo">` and `<div data-test-whatever='foo'>` (single quotes), but I can imagine situations where it's just too complex to do this kind of preprocessing with regular expressions.

**Is there any point in the parsing process in which templates are parsed into an AST in which we can run transformations**? That would be a much safer way of writing preprocessors.

**Comment by lukeed** [comment]
While you may be using the Rollup plugin as part of your question, the question actually has nothing to do with `rollup-plugin-svelte` at all.

You could dive into a combination of `svelte.parse` with `svelte.walk` to work at an AST level instead of a RegExp level, though. But it's certainly something you'd have to _bring to_ this plugin – it's not something the plugin is responsible for.

Hope that helps, however late it might be 😅
