### ISSUE TITLE
emitCss: true causes Error: Identifier directly after number

### ISSUE THREAD

**Issue by afreidz** [sveltejs/rollup-plugin-svelte#89]
**Using `emitCss: true` causes an error in the rollup build**

Rollup Version: `1.28.0`
Plugin Version: `5.1.1`

_rollup.config.js:_
```js
import path from 'path';
import svelte from 'rollup-plugin-svelte';
import autoPreprocess from 'svelte-preprocess';

export default {
  input: {
    test: path.join(process.cwd(), 'Test.svelte'),
  },
  plugins: [
    svelte({
      emitCss: true,
      preprocess: autoPreprocess(),
    }),
  ]
};
````

_Test.svelte_
```html
<ul>
  {#each items as item}
  <li>{item}></li>
  {/each}
</ul>

<style type="text/less">
  @test: none;
  ul {
    list-style-type: @test;
  }
</style>

<script>
  export let items = ['foo', 'bar'];
</script>
```

_package.json_
```json
{
  "devDependencies": {
    "less": "^3.10.3",
    "rollup": "^1.28.0",
    "rollup-plugin-svelte": "^5.1.1",
    "svelte": "^3.16.7",
    "svelte-preprocess": "^3.3.0"
  }
}
```

then run:
`npm i`
`npx rollup -c rollup.config.js`

**Result:**
```
Test.svelte → stdout...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
svelte/internal (imported by Test.svelte)
[!] Error: Identifier directly after number (Note that you need plugins to import files that are not JavaScript)
Test.css (1:11)
1: ul.svelte-1wrqd9u{list-style-type:none}
              ^
2: /*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVGVzdC5zdmVsdGUiLCJzb3VyY2VzIjpbIlRlc3Quc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjx1bD5cbiAgeyNlYWNoIGl0ZW1zIGFzIGl0ZW19XG4gIDxsaT57aXRlbX0+PC9saT5cbiAgey9lYWNofVxuPC91bD5cblxuPHN0eWxlIHR5cGU9XCJ0ZXh0L2xlc3NcIj51bCB7XG4gIGxpc3Qtc3R5bGUtdHlwZTogbm9uZTtcbn1cbjwvc3R5bGU+XG5cbjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgaXRlbXMgPSBbJ2ZvbycsICdiYXInXTtcbjwvc2NyaXB0PiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFNd0IsRUFBRSxlQUFDLENBQUMsQUFDMUIsZUFBZSxDQUFFLElBQUksQUFDdkIsQ0FBQyJ9 */
Error: Identifier directly after number (Note that you need plugins to import files that are not JavaScript)
```

If you remove `emitCss: true` from the rollup config, the build will complete as expected.

**Comment by afreidz** [comment]
**Additional findings:**  it seems as though handling the css in another rollup plugin will prevent this error from happening.  However I'm not sure this behavior is clear/correct?  Either the documentation should be updated to reflect that build errors will occur if you `emitCss` and do NOT handle it in another plugin, or the plugin should be updated to treat `emitCss:true` (with no further plugins to handle them) the same as omitting the option.

**Comment by GautamBose** [comment]
Yup, this should at least be removed from the example script.

**Comment by kubido** [comment]
also even if I pass `emitCss: true` the other plugin didn't receive the `files.css` value. 
`files.css` is undefined

**Comment by lukeed** [comment]
By using `emitCss: true`, something like this has always been added to your JS output file:

```js
// example.js
import "./path/to/example.css";
```

It _requires_ another Rollup plugin to deal with that `import` statement and continue processing from there. The role of `rollup-plugin-svelte` ends at the `load()` phase, where it returns the styles belonging to that virtual CSS file (`./path/to/example.css` in this case). From there on, the new Rollup plugin is completely in control.

The documentation has been updated in #147 to make this clearer.
