### ISSUE TITLE
Unused CSS Selector warning not appearing

### ISSUE THREAD

**Issue by mustafa0x** [sveltejs/rollup-plugin-svelte#94]
It shows in the REPL, but not when running locally.

**Comment by mhatvan** [comment]
I think this issue can be closed, just verified that it reports any unused styles.

![2020-06-25_10-37](https://user-images.githubusercontent.com/16797721/85686295-1df0e200-b6d0-11ea-985f-1a05023d3211.png)

**Comment by mustafa0x** [comment]
I'm still not getting warnings.

```json
{
  "devDependencies": {
    "npm-run-all": "^4.1.5",
    "rollup": "^2.18.1",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-livereload": "^1.3.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-svelte": "^5.2.3",
    "rollup-plugin-terser": "^6.1.0",
    "sirv-cli": "^1.0.2",
    "svelte-routing": "^1.4.2",
    "svelte": "^3.23.2"
  }
}
```

**Comment by mhatvan** [comment]
Not sure if that is the actual problem, but you are using some outdated packages:
``` 
"@rollup/plugin-commonjs": "^13.0.0",
"@rollup/plugin-node-resolve": "^8.1.0"
```
These rollup dependencies switched to scoped package naming, so you are actually behind my 3 major versions.

**Comment by mustafa0x** [comment]
Thanks, didn't help though. I also tried now with a fresh instance of [svelte-template](https://github.com/sveltejs/template/).

**Comment by Bravilogy** [comment]
@mustafa0x Hi, did you figure this out? I have the same exact issue here..

**Comment by mustafa0x** [comment]
No, I didn't. I still don't get any warnings.

**Comment by mustafa0x** [comment]
Line of code that is causing this:
https://github.com/sveltejs/rollup-plugin-svelte/blob/master/index.js#L255

The issue where Rich clarifies the motivation:
https://github.com/sveltejs/rollup-plugin-svelte/pull/17

The PR where the code was committed.
https://github.com/sveltejs/rollup-plugin-svelte/pull/22

So, in light of the above it seems this error was supposed to be silenced only `css: false`.

**Comment by Bravilogy** [comment]
@mustafa0x thank you, that's very helpful! I was just starting to dig into the code myself. :)
